"""initial tables

Revision ID: a24692fe417a
Revises: 
Create Date: 2025-11-29 17:53:40.865555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24692fe417a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sairport',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('mandt', 'id')
    )
    op.create_table('scarr',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.String(length=3), nullable=False),
    sa.Column('carrname', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('mandt', 'carrid')
    )
    op.create_table('scust',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('mandt', 'id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('sbook',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.String(length=3), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('fldate', sa.DateTime(), nullable=False),
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('custom_mandt', sa.String(length=3), nullable=True),
    sa.Column('custom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['custom_mandt', 'custom_id'], ['scust.mandt', 'scust.id'], ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid', 'fldate', 'bookid')
    )
    op.create_table('sflight',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.String(length=3), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('fldate', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('planetype', sa.String(length=10), nullable=True),
    sa.Column('seatsmax', sa.Integer(), nullable=True),
    sa.Column('seatssocc', sa.Integer(), nullable=True),
    sa.Column('airpfrom_id', sa.Integer(), nullable=True),
    sa.Column('airpto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mandt', 'airpfrom_id'], ['sairport.mandt', 'sairport.id'], ),
    sa.ForeignKeyConstraint(['mandt', 'airpto_id'], ['sairport.mandt', 'sairport.id'], ),
    sa.ForeignKeyConstraint(['mandt', 'carrid'], ['scarr.mandt', 'scarr.carrid'], ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid', 'fldate')
    )
    op.create_table('spfli',
    sa.Column('mandt', sa.String(length=3), nullable=False),
    sa.Column('carrid', sa.String(length=3), nullable=False),
    sa.Column('connid', sa.String(length=4), nullable=False),
    sa.Column('fldate', sa.DateTime(), nullable=False),
    sa.Column('countryfr', sa.String(length=3), nullable=True),
    sa.Column('cityfrom', sa.String(length=20), nullable=True),
    sa.Column('airpfrom', sa.String(length=3), nullable=True),
    sa.Column('countryto', sa.String(length=3), nullable=True),
    sa.Column('cityto', sa.String(length=20), nullable=True),
    sa.Column('airpto', sa.String(length=3), nullable=True),
    sa.Column('fltime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mandt', 'carrid', 'connid', 'fldate'], ['sflight.mandt', 'sflight.carrid', 'sflight.connid', 'sflight.fldate'], ),
    sa.PrimaryKeyConstraint('mandt', 'carrid', 'connid', 'fldate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spfli')
    op.drop_table('sflight')
    op.drop_table('sbook')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scust')
    op.drop_table('scarr')
    op.drop_table('sairport')
    # ### end Alembic commands ###
